# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gatherly.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egatherly.proto\x12\x08gatherly\"\x1d\n\x08KmerHash\x12\x11\n\tkmer_hash\x18\x01 \x01(\x03\"\x1e\n\x0bKmerSources\x12\x0f\n\x07sources\x18\x01 \x01(\t\".\n\x0bsourmashSig\x12\x10\n\x08sig_path\x18\x01 \x01(\t\x12\r\n\x05kSize\x18\x02 \x01(\x03\".\n\tFASTXFile\x12\x12\n\nfastx_path\x18\x01 \x01(\t\x12\r\n\x05kSize\x18\x02 \x01(\x03\"\x1a\n\x07Sources\x12\x0f\n\x07sources\x18\x01 \x01(\t2\xba\x01\n\x08Gatherly\x12:\n\x0bgather_kmer\x12\x12.gatherly.KmerHash\x1a\x15.gatherly.KmerSources\"\x00\x12\x38\n\ngather_sig\x12\x15.gatherly.sourmashSig\x1a\x11.gatherly.Sources\"\x00\x12\x38\n\x0cgather_fastx\x12\x13.gatherly.FASTXFile\x1a\x11.gatherly.Sources\"\x00\x62\x06proto3')



_KMERHASH = DESCRIPTOR.message_types_by_name['KmerHash']
_KMERSOURCES = DESCRIPTOR.message_types_by_name['KmerSources']
_SOURMASHSIG = DESCRIPTOR.message_types_by_name['sourmashSig']
_FASTXFILE = DESCRIPTOR.message_types_by_name['FASTXFile']
_SOURCES = DESCRIPTOR.message_types_by_name['Sources']
KmerHash = _reflection.GeneratedProtocolMessageType('KmerHash', (_message.Message,), {
  'DESCRIPTOR' : _KMERHASH,
  '__module__' : 'gatherly_pb2'
  # @@protoc_insertion_point(class_scope:gatherly.KmerHash)
  })
_sym_db.RegisterMessage(KmerHash)

KmerSources = _reflection.GeneratedProtocolMessageType('KmerSources', (_message.Message,), {
  'DESCRIPTOR' : _KMERSOURCES,
  '__module__' : 'gatherly_pb2'
  # @@protoc_insertion_point(class_scope:gatherly.KmerSources)
  })
_sym_db.RegisterMessage(KmerSources)

sourmashSig = _reflection.GeneratedProtocolMessageType('sourmashSig', (_message.Message,), {
  'DESCRIPTOR' : _SOURMASHSIG,
  '__module__' : 'gatherly_pb2'
  # @@protoc_insertion_point(class_scope:gatherly.sourmashSig)
  })
_sym_db.RegisterMessage(sourmashSig)

FASTXFile = _reflection.GeneratedProtocolMessageType('FASTXFile', (_message.Message,), {
  'DESCRIPTOR' : _FASTXFILE,
  '__module__' : 'gatherly_pb2'
  # @@protoc_insertion_point(class_scope:gatherly.FASTXFile)
  })
_sym_db.RegisterMessage(FASTXFile)

Sources = _reflection.GeneratedProtocolMessageType('Sources', (_message.Message,), {
  'DESCRIPTOR' : _SOURCES,
  '__module__' : 'gatherly_pb2'
  # @@protoc_insertion_point(class_scope:gatherly.Sources)
  })
_sym_db.RegisterMessage(Sources)

_GATHERLY = DESCRIPTOR.services_by_name['Gatherly']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KMERHASH._serialized_start=28
  _KMERHASH._serialized_end=57
  _KMERSOURCES._serialized_start=59
  _KMERSOURCES._serialized_end=89
  _SOURMASHSIG._serialized_start=91
  _SOURMASHSIG._serialized_end=137
  _FASTXFILE._serialized_start=139
  _FASTXFILE._serialized_end=185
  _SOURCES._serialized_start=187
  _SOURCES._serialized_end=213
  _GATHERLY._serialized_start=216
  _GATHERLY._serialized_end=402
# @@protoc_insertion_point(module_scope)
